//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAtaskTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class product
    {
        [Column("id")]
        public int Id { get; set; }
        [Column("name")]
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        [Column("image")]
        public string Image { get; set; }
        [Column("description")]
        public string Description { get; set; }
        public Nullable<int> CID { get; set; }
    
        public virtual category category { get; set; }
    }
}
